spring:
  application:
    name: mcp
  ai:
    mcp:
      server:
        annotation-scanner:
          enabled: true
        instructions: This MCP server offers various tools to get product information and manage customer carts.
